# Basic Information 
title: Alex Noh
alternate_name: Heesuk Noh
position: Undergraduate Researcher
affiliation: Simon Fraser University
email: hna57 (at) sfu.ca

# Search Engine Optimization (SEO)
# The following information is used to improve the website traffic from search engines, e.g., Google.
keywords: Alex Noh, Heesuk Noh, human-computer interaction, human-AI interaction, extended reality, accessibility, ADHD
description: Alex Noh, also known as Heesuk Noh, is an HCI researcher at Simon Fraser University studying human-AI interaction, XR, and cognitive accessibility.
canonical: https://ndh707.github.io/

# Links 
# If you don't need one of them, you may delete the corresponding line.
google_scholar: https://scholar.google.com/citations?user=XUBvJwoAAAAJ&hl=en
cv_link: assets/files/curriculum_vitae.pdf
linkedin: https://www.linkedin.com/in/alex-noh-0739a2159/

# Images (e.g., your profile picture and your website's favicon) 
# "favicon" and "favicon_dark" are used for the light and dark modes, respectively. 
avatar: ./assets/img/profile.jpeg
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png

# Footnote
# You may use the option to disable the footnote, "Powered by Jekyll and Minimal Light theme."
enable_footnote: false

# Auto Dark Mode
# You may use the option to disable the automatic dark theme
auto_dark_mode: false

# Font
# You can use this option to choose between Serif or Sans Serif fonts.
font: "Serif" # or "Sans Serif"

# Use this project as a remote theme for GitHub Pages
# See the guide here: https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/adding-a-theme-to-your-github-pages-site-using-jekyll
remote_theme: yaoyao-liu/minimal-light

# The following files will be removed from the generated website.
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - README_zh_Hans.md
  - README_zh_Hant.md
  - README_de.md
  - LICENSE
  - minimal-light.gemspec
  - html_source_file/
